# Generated by Django 3.1.7 on 2021-06-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_commenttopost_citation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttopost',
            name='content',
        ),
        migrations.AddField(
            model_name='commenttopost',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
