# Generated by Django 3.1.7 on 2021-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210626_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='post_reputation',
            field=models.IntegerField(default=0),
        ),
    ]
