# Generated by Django 3.1.7 on 2021-06-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_forumpost_post_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='people_voted',
            field=models.IntegerField(default=0),
        ),
    ]
