# Generated by Django 3.1.7 on 2021-04-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='min_words_in_post_to_see',
        ),
        migrations.AddField(
            model_name='post',
            name='preview_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
