# Generated by Django 4.2.16 on 2024-11-10 07:29

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityemailmessage',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
    ]
