# Generated by Django 3.1.7 on 2021-04-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_contactemails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactEmails',
            new_name='ContactEmail',
        ),
    ]
