# Generated by Django 3.1.7 on 2021-04-16 16:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210410_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('topic', models.CharField(choices=[('Bug on website', 'Bug on website'), ('Suggestions', 'Suggestions'), ('Help', 'Help'), ('Bug on server', 'Bug on server'), ('Bug with plugins', 'Bug with plugins'), ('Other', 'Other')], max_length=100, null=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
