# Generated by Django 3.1.7 on 2021-05-12 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatwith',
            name='name',
        ),
        migrations.AddField(
            model_name='chatwith',
            name='user_qs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_qs_table', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatwith',
            name='user_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_second_table', to=settings.AUTH_USER_MODEL),
        ),
    ]
