# Generated by Django 3.1.7 on 2021-04-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='theme',
            new_name='topic',
        ),
    ]
