# Generated by Django 3.1.7 on 2021-06-26 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210529_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttopost',
            name='citation',
        ),
    ]
