# Generated by Django 3.1.7 on 2021-04-11 05:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210409_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
