# Generated by Django 3.1.7 on 2021-04-11 06:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210411_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
