# Generated by Django 3.1.7 on 2021-04-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_forumpost_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='owner',
        ),
    ]
