# Generated by Django 3.1.7 on 2021-05-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_chat_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_line',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chat.chat'),
        ),
    ]
