# Generated by Django 3.1.7 on 2021-08-03 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_auto_20210721_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.IntegerField(default=0)),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appraiser_to_Usermodel', to=settings.AUTH_USER_MODEL)),
                ('assessed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assessed_to_ForumPost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
