# Generated by Django 3.1.7 on 2021-08-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_reputation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='reputation',
            field=models.IntegerField(default='0'),
        ),
    ]
