# Generated by Django 3.1.7 on 2021-06-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210410_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='date_of_birth',
        ),
    ]
