# Generated by Django 3.1.7 on 2021-06-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_forumpost_people_voted'),
        ('authentication', '0007_auto_20210627_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='Opinion_posts',
            field=models.ManyToManyField(blank=True, to='forum.ForumPost'),
        ),
    ]
