# Generated by Django 3.1.7 on 2021-06-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_profile_opinion_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='Opinion_posts',
            new_name='opinion_posts',
        ),
    ]
