# Generated by Django 3.1.7 on 2021-04-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210409_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='reptutation',
            new_name='reputation',
        ),
    ]
