# Generated by Django 3.1.7 on 2021-04-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210409_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='reputation',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
    ]
