# Generated by Django 3.1.7 on 2021-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
