# Generated by Django 3.1.7 on 2021-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='description',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
    ]
