# Generated by Django 3.1.7 on 2021-06-28 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_forumpost_people_voted'),
        ('authentication', '0009_auto_20210628_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='reputation_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_to_ForumPost', to='forum.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_to_Usermodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
