# Generated by Django 3.1.7 on 2021-06-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_reputation_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reputation_post',
        ),
    ]
